### ISSUE TITLE
Automatic upload of results

### ISSUE THREAD

**Issue by MiraPurkrabek** [MiraPurkrabek/PoseAnnotator#1]
At the moment, the tool runs completely locally. It is beneficial for data privacy but risk loosing hours of work when one JSON file gets corrupted or lost. The problem could be solved by (optional) automatic upload of JSON file with results to the cloud. The job would be backed-up and supervisor can check annotator's job in real-time.

**Required features**
- uplad JSON with annotations to cloud after every app exit (or choose other appropriate interval)
- use optional flag to enable the feature. Default behavior would stay local to protect privacy  
- upload only JSON with results NOT THE DATA to allow workflow with sensitive data

**Comment by Fizza-Rubab** [comment]
Hi! Which cloud service should be used for upload?

**Comment by MiraPurkrabek** [comment]
Hi, I didn't have any specific one in mind. The use case is to have the ability to remotely check the progress of contractors and having backup in case something goes wrong.

I thought that it might be Google Drive since it provides some basic free storage and is easily sharable.

Do you have any implementation in mind?

**Comment by Fizza-Rubab** [comment]
The intended usage makes sense. 

Backing up after annotating every n (maybe 10?) images or so would be safer than doing it after exiting the app. I was also thinking of implementing this with Google Drive but connecting to the Google Drive API isn't very straightforward. A more user-friendly alternative could be Dropbox, but it has only 2GB of free storage which wouldn't be sufficient when annotating large datasets.

I can add a Google Drive implementation though.

**Comment by MiraPurkrabek** [comment]
Solved by #3
